### ISSUE TITLE
Akka.TestKit.NUnit nuget is still at version 1.2.1

### ISSUE THREAD

**Issue by gengle** [akkadotnet/Akka.TestKit.Nunit#20]
Not sure if this was an over site but I see Akka.TestKit.NUnit nuget is still at 1.2.1 instead of the 1.2.3
https://www.nuget.org/packages/Akka.TestKit.NUnit/

**Comment by gengle** [comment]
I'll submit a PR shortly

**Comment by Danthar** [comment]
Closed via #21
